public class Clwyfd {
    public static void main() {
        System.out.println("gvfva");
        System.out.println("vjipc");
        System.out.println("pdcld");
        System.out.println("froam");
        System.out.println("hdurl");
        System.out.println("nnndd");
        System.out.println("bfylv");
        System.out.println("rqfcn");
        System.out.println("khlhu");
        System.out.println("kgiah");
        System.out.println("jgjxu");
        System.out.println("gnhwg");
        System.out.println("mjbri");
        System.out.println("tbuvt");
        System.out.println("qggpn");
        System.out.println("rblrg");
        System.out.println("nscwe");
        System.out.println("fukwx");
        System.out.println("nvveo");
        System.out.println("qapcj");
        System.out.println("jocuo");
        System.out.println("lvjhd");
        System.out.println("yabae");
        System.out.println("offyb");
        System.out.println("bkgpe");
        System.out.println("vqbkf");
        System.out.println("coyfe");
        System.out.println("yfglg");
        System.out.println("etarj");
        System.out.println("mnkkc");
        System.out.println("wkdnv");
        System.out.println("xdrsd");
        System.out.println("jlmhh");
        System.out.println("hjdfw");
        System.out.println("siwof");
        System.out.println("eahiu");
        System.out.println("yuqlg");
        System.out.println("ixryg");
        System.out.println("oedky");
        System.out.println("ykirm");
    }
}
